sudo: required
services:
  - docker

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build --tag myimage .
- docker run myimage

after_script:
- docker images
